### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by sora-site** [sora-site/protospace-40734#1]
#URL
https://protospace-40734.onrender.com/

**Comment by yuri240** [comment]
**@sora-site**さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by sora-site** [comment]
ありがとうございました
